# See: Travis Support did recomment moving Android builds to GCE.
# Which is on 'precise' and has larger VMs: https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required
dist: precise

language: android
jdk:
  - oraclejdk8

notifications:
  irc: irc.freenode.org#feedhenry

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services

env:
  global:
    - RELEASE_VERSION=$(grep "<version>" fh-android-sdk/pom.xml | tr "\n" ":" | cut -d ':' -f1 | sed s/\<version\>//g| sed s/\"//g| sed s/\<\\/version\>//g | tr -d ' ')
    - ANDROID_SDK=android-23 
  matrix:
    - ANDROID_SDK="android-24" ANDROID_EMULATOR="android-16"  ANDROID_ABI=google_apis/armeabi-v7a   ANDROID_PKGS=addon-google_apis-google-16,sys-img-armeabi-v7a-google_apis-16
    - ANDROID_SDK="android-24" ANDROID_EMULATOR="android-17"  ANDROID_ABI=google_apis/armeabi-v7a   ANDROID_PKGS=addon-google_apis-google-17,sys-img-armeabi-v7a-google_apis-17
    - ANDROID_SDK="android-24" ANDROID_EMULATOR="android-18"  ANDROID_ABI=google_apis/armeabi-v7a   ANDROID_PKGS=addon-google_apis-google-18,sys-img-armeabi-v7a-google_apis-18
    - ANDROID_SDK="android-24" ANDROID_EMULATOR="android-19"  ANDROID_ABI=google_apis/armeabi-v7a   ANDROID_PKGS=addon-google_apis-google-19,sys-img-armeabi-v7a-google_apis-19
    - ANDROID_SDK="android-24" ANDROID_EMULATOR="android-21"  ANDROID_ABI=google_apis/armeabi-v7a   ANDROID_PKGS=addon-google_apis-google-21,sys-img-armeabi-v7a-google_apis-21
    - ANDROID_SDK="android-24" ANDROID_EMULATOR="android-22"  ANDROID_ABI=google_apis/armeabi-v7a   ANDROID_PKGS=addon-google_apis-google-22,sys-img-armeabi-v7a-google_apis-22
    #- ANDROID_SDK="android-24" ANDROID_EMULATOR="android-23"  ANDROID_ABI=google_apis/armeabi-v7a   ANDROID_PKGS=addon-google_apis-google-23,sys-img-armeabi-v7a-google_apis-23
    - ANDROID_SDK="android-24" ANDROID_EMULATOR="android-24"  ANDROID_ABI=google_apis/armeabi-v7a   ANDROID_PKGS=addon-google_apis-google-24,sys-img-armeabi-v7a-google_apis-24


before_install:
  - echo y | android update sdk -a -u -t ${ANDROID_PKGS:-}

  # Checkout maven-android-sdk-deployer
  - git clone git://github.com/mosabua/maven-android-sdk-deployer.git

  # Install Android in locally Maven repository
  - cd $PWD/maven-android-sdk-deployer/platforms/$ANDROID_SDK
  - mvn install -N --quiet
  - cd -

  # Install locally google-m2repository (including play services aar)
  - cd $PWD/maven-android-sdk-deployer/repositories
  - mvn install --quiet
  - cd -

install:
  - echo no | android create avd --force -n test -t "$ANDROID_EMULATOR" --abi "$ANDROID_ABI"
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device get-serialno
  - mvn --version
  - mvn clean

before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - mvn install -Drelease
  - cd fh-android-sdk-test
  - mvn clean package -DskipTests=true;
  - adb shell df
  - adb install target/fh-android-sdk-test-$RELEASE_VERSION.apk
  - mvn android:instrument

after_script:
  - cat logcat.log; pkill -KILL -f adb

